Print numbers
kapilchandrawal/problems-ruby pull request #1
Opened 2022-01-13 08:22 UTC by kapilchandrawal

2022-01-14 05:52 UTC, kalpana19sharma requested changes
@kapilchandrawal Please fix indentation and code styles in all of your files and use a proper heading for you PR.

2022-01-14 05:52 UTC, kalpana19sharma commented on double-numbers-using-map.rb
> +# Use the map function to double all the elements in the array.
Use `_` in the filenames instead of `-`.

2022-01-14 05:52 UTC, kalpana19sharma commented on double-numbers-using-map.rb
> +arr = [2,4,6,8]
Add spaces after `,`

2022-01-14 05:52 UTC, kalpana19sharma commented on double-numbers-using-map.rb
> +}
Use `do..end` syntax for multi-line blocks otherwise write the logic in single line.
 ```suggestion
new_arr = arr.map { |a| a * 2 }
```

2022-01-14 05:52 UTC, kalpana19sharma commented on double-numbers-using-map.rb
> +print new_arr
Add new line at the end of the file.

2022-01-14 05:52 UTC, kalpana19sharma commented on join-2arrays-using-inbuilt.rb
> +arr1 = ["Hello", "world"]
Use `%w` syntax for array of strings.
https://github.com/github/rubocop-github/blob/master/STYLEGUIDE.md#collections

2022-01-14 05:52 UTC, kalpana19sharma commented on join-array-without-inbuilt.rb
> +
Fix the indentation and code styles. Use 2 space indentation.

2022-01-14 07:40 UTC, kapilchandrawal commented on double-numbers-using-map.rb
> +# Use the map function to double all the elements in the array.
Changed the filesnames

2022-01-14 07:57 UTC, kapilchandrawal commented on double-numbers-using-map.rb
> +arr = [2,4,6,8]
Added space after commas
arr = [2, 4, 6, 8]

2022-01-14 07:59 UTC, kapilchandrawal commented
I have made changes according to your suggestions, please review it once again

2022-01-17 07:03 UTC, kalpana19sharma requested changes

2022-01-17 07:03 UTC, kalpana19sharma commented on .vscode/settings.json
> +{
Don't commit this file

2022-01-17 07:03 UTC, kalpana19sharma commented on join_array_without_inbuilt.rb
> +end
Use 2 space indentation

2022-01-17 07:03 UTC, kalpana19sharma commented on map_method.rb
> +end
Use 2 space indentation

2022-01-17 07:03 UTC, kalpana19sharma commented on number_print.rb
> +end
Use 2 space indentation

2022-01-17 07:03 UTC, kalpana19sharma commented on occurence_of_characters.rb
> +  end
Fix the indentation

2022-01-20 09:01 UTC, kapilchandrawal commented on .vscode/settings.json
> +{
Removed this file

2022-01-20 11:47 UTC, kapilchandrawal commented on join_array_without_inbuilt.rb
> +end
Used the 2 space indentation

2022-01-20 11:47 UTC, kapilchandrawal commented on occurence_of_characters.rb
> +  end
Fixed the indentation

2022-01-24 02:59 UTC, kalpana19sharma approved these changes

2022-01-24 02:59 UTC, merged